# -*- coding: utf-8 -*-
"""food_identification_cvnlp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hF-ZF54WLE_4yOLiiEt6H9ONdAScH44G

# Import Libraries
"""

# Import Libraries

# Standard Libraries
import itertools
import os
import warnings
import zipfile

# Third-Party Libraries
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix

# TensorFlow and Keras Components
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, Model, Sequential
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.layers import RandomFlip, RandomRotation, GlobalAveragePooling2D, Dense, Dropout, Rescaling
from tensorflow.keras.optimizers import Adam

warnings.filterwarnings('ignore')

"""# Load Dataset"""

# Define dataset path

dataset_path = "/content/food_dataset.zip"  # Note:
# This notebook is configured for Google Colab, where the dataset
# is uploaded to the /content directory. If running locally,
# modify the dataset_path variable to match your local file location.


print("Food11 Dataset Path:", dataset_path)

# Global Setup (Seeds and Parameters)
np.random.seed(42)
tf.random.set_seed(42)

# Image Dimensions and Batching
IMG_HEIGHT = 224
IMG_WIDTH = 224
BATCH_SIZE = 32

# Training Schedule
EPOCHS_PHASE1=15
EPOCHS_PHASE2=10
FINE_TUNE_START_LAYER_INDEX = -4

# Data Loading
def load_food_dataset(data_path, img_height, img_width, batch_size):
    """
    Handles dataset file extraction and loads image data from
    'training', 'validation', and 'evaluation' subdirectories using
    tf.keras.utils.image_dataset_from_directory.
    """

    if os.path.isfile(data_path) and data_path.endswith('.zip') and zipfile.is_zipfile(data_path):
        extract_path = '/content/food_dataset'  # Temporary extraction directory
        if not os.path.exists(extract_path):
            os.makedirs(extract_path)
        with zipfile.ZipFile(data_path, 'r') as zip_ref:
            zip_ref.extractall(extract_path) # Extract zip contents
        data_path = extract_path

    data_root_dir = os.path.join(data_path)

    # Basic directory checks
    if not os.path.exists(data_root_dir):
      print(f"Training directory not found at {data_root_dir}")
      if os.path.isdir(data_path):
          print("Available directories:", os.listdir(data_path))
      else:
          print(f"{data_path} is not a directory. Please check the path.")

    train_dir = os.path.join(data_root_dir, 'training')
    val_dir = os.path.join(data_root_dir, 'validation')
    test_dir = os.path.join(data_root_dir, 'evaluation')

    def load_ds(path, subset_name, shuffle):
        """Helper to load one dataset subset (train, val, or test)."""
        print(f"Loading {subset_name} data from {path}")
        ds = tf.keras.utils.image_dataset_from_directory(
            path,
            labels='inferred',
            label_mode='categorical', # Output: one-hot encoded labels
            image_size=(img_height, img_width),
            batch_size=batch_size,
            shuffle=shuffle
        )
        return ds

    # Load the three dataset splits
    train_ds = load_ds(train_dir, 'Training', shuffle=True)
    val_ds = load_ds(val_dir, 'Validation', shuffle=False)
    test_ds = load_ds(test_dir, 'Test/Evaluation', shuffle=False)

    class_names = train_ds.class_names
    NUM_CLASSES = len(class_names)


    def configure_ds(ds):
        """Applies normalization and performance optimizations (NO CACHING)."""
        # Rescale inputs from [0, 255] to [0, 1] for MobileNetV2 input requirements
        normalization_layer = Rescaling(1./255)
        ds = ds.map(lambda x, y: (normalization_layer(x), y))
        # Prefetching allows the data processing pipeline to work concurrently with model training
        ds = ds.prefetch(buffer_size=tf.data.AUTOTUNE)
        return ds

    # Apply configuration to all datasets
    train_ds = configure_ds(train_ds)
    val_ds = configure_ds(val_ds)
    test_ds = configure_ds(test_ds)

    # Reporting
    print("\nData Loading Summary")
    print(f"Found {NUM_CLASSES} food classes: {class_names}")

    # Total images loaded
    total_images = sum(len(files) for _, _, files in os.walk(train_dir))
    print(f"Total Training Images Loaded: {total_images}")
    print(f"Image shape: ({img_height}, {img_width}, 3)")

    return train_ds, val_ds, test_ds, class_names, NUM_CLASSES, train_dir

# Execution
train_ds, val_ds, test_ds, class_names, NUM_CLASSES, train_dir = load_food_dataset(
    dataset_path, IMG_HEIGHT, IMG_WIDTH, BATCH_SIZE)

"""#Prepare Dataset"""

def display_one_image_per_class(train_dir, class_names, img_height, img_width):
    """
    Reads and plots one sample image from each class directory in the training set
    to visually verify that all classes are present and load correctly.
    """
    print(f"\nDisplaying One Sample Image Per Class ({len(class_names)} Classes)")

    # Determine the best grid size
    num_classes = len(class_names)
    cols = int(np.ceil(np.sqrt(num_classes)))
    rows = int(np.ceil(num_classes / cols))

    plt.figure(figsize=(cols * 3, rows * 3))

    for i, class_name in enumerate(sorted(class_names)):
        class_path = os.path.join(train_dir, class_name)
        if os.path.isdir(class_path):
            file_list = [f for f in os.listdir(class_path) if f.lower().endswith(('.png', '.jpg', '.jpeg'))]
            if file_list:
                # Get the first image file found in the directory
                img_path = os.path.join(class_path, file_list[0])

                # Load the image using tf.keras.utils.load_img
                img = tf.keras.utils.load_img(img_path, target_size=(img_height, img_width))
                img_array = tf.keras.utils.img_to_array(img)

                # Plotting
                ax = plt.subplot(rows, cols, i + 1)
                # Rescale the image array from [0, 255] for display
                plt.imshow(img_array.astype("uint8"))

                plt.title(f"{class_name}", fontsize=10)
                plt.axis("off")
            else:
                print(f"Warning: No images found in {class_name} directory.")
        else:
            print(f"Warning: Class directory not found for {class_name}.")

    plt.tight_layout()
    plt.show()

display_one_image_per_class(train_dir, class_names, IMG_HEIGHT, IMG_WIDTH)

"""# Define Performance Matrix"""

def plot_history(history):
    """Plots training and validation accuracy and loss over epochs."""

    # Extract metrics from the history object dictionary
    acc = history.history['accuracy']
    val_acc = history.history['val_accuracy']
    loss = history.history['loss']
    val_loss = history.history['val_loss']

    # Create the range of epoch numbers for the X-axis
    epochs_range = range(len(acc))

    plt.figure(figsize=(12, 5))

    # Plot 1: Accuracy
    plt.subplot(1, 2, 1)
    plt.plot(epochs_range, acc, label='Training Accuracy', color='blue')
    plt.plot(epochs_range, val_acc, label='Validation Accuracy', color='red')
    plt.title('Training and Validation Accuracy')
    plt.xlabel('Epoch')
    plt.ylabel('Accuracy')
    plt.legend(loc='lower right')

    # Plot 2: Loss
    plt.subplot(1, 2, 2)
    plt.plot(epochs_range, loss, label='Training Loss', color='blue')
    plt.plot(epochs_range, val_loss, label='Validation Loss', color='red')
    plt.title('Training and Validation Loss')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.legend(loc='upper right')
    plt.show()

def plot_confusion_matrix(cm, class_names, title='Confusion Matrix', cmap=plt.cm.Blues):
    """Prints and plots the confusion matrix."""
    plt.figure(figsize=(10, 8))

    # Display the confusion matrix using a color map
    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()

    # Set axis ticks and labels
    tick_marks = np.arange(len(class_names))
    plt.xticks(tick_marks, class_names, rotation=45, ha='right')
    plt.yticks(tick_marks, class_names)

    # Normalize the matrix for better visualization
    cm_normalized = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]

    # Add text annotations to the plot
    thresh = cm.max() / 2.
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j, i, format(cm[i, j], 'd'),
                 horizontalalignment="center",
                 color="white" if cm[i, j] > thresh else "black")

    plt.ylabel('True label')
    plt.xlabel('Predicted label')
    plt.tight_layout()
    plt.show()

# Extract True Labels
all_true_labels = []
for _, labels in test_ds:
    all_true_labels.append(tf.argmax(labels, axis=1).numpy())
true_labels_int = np.concatenate(all_true_labels, axis=0)

"""# Define CNN Model: Transfer Learning Model using MobileNetV2"""

def setup_training_callbacks(patience):
    """
    Configure callbacks for optimal training: EarlyStopping and Learning Rate Reduction.
    EarlyStopping: Stops training when validation accuracy stops improving for 'patience' number of epochs.
    ReduceLROnPlateau: Reduces the learning rate by half if validation loss plateaus (no improvement after 2 epochs).
    """
    print("\nConfiguring Keras Callbacks")

    # Early stopping to prevent overfitting
    early_stopping = EarlyStopping(
        monitor='val_accuracy', # Metric to monitor
        patience= patience, # Number of epochs with no improvement after which training will be stopped
        restore_best_weights=True, # Restores model weights from the epoch with the best monitored value
        verbose=1,
        mode='max' # Look for maximum val_accuracy
    )

    # Learning rate reduction when training plateaus
    lr_reduction = ReduceLROnPlateau(
        monitor='val_loss',
        patience=2, # Number of epochs with no improvement before reducing LR
        factor=0.5, # Factor by which the learning rate will be reduced
        min_lr=1e-6,
        verbose=1,
        mode='min' # Look for minimum val_loss
    )

    return [early_stopping, lr_reduction]

def create_food_classification_model(input_shape, num_classes):
    """
    Creates a Transfer Learning model using MobileNetV2 base, initially frozen for Feature Extraction.
    """
    # Load Pre-trained Base Model (MobileNetV2)
    base_model = MobileNetV2(
        weights='imagenet', # Use weights pre-trained on the ImageNet dataset
        include_top=False, # Exclude the final classification layer of MobileNetV2
        input_shape=input_shape
    )

    # Freeze the Base Model Layers (Feature Extraction Strategy)
    base_model.trainable = False

    inputs = keras.Input(shape=input_shape)

    # Data Augmentation layer to introduce randomness and increase the effective dataset size
    data_augmentation = Sequential([
    RandomFlip("horizontal"),
    RandomRotation(0.1),
    ], name='data_augmentation')

    x = data_augmentation(inputs)

    # Pass input through the frozen MobileNetV2 base
    x = base_model(x, training=False)

    # Apply classifier head layers:
    # Global Average Pooling reduces the spatial dimensions to 1, preparing for the dense layers
    x = GlobalAveragePooling2D(name='global_avg_pool')(x)

    # First dense layer with ReLU activation
    x = Dense(1024, activation='relu', name='dense_1024')(x)
    # Dropout layer for regularization to prevent overfitting
    x = Dropout(0.5, name='dropout_1')(x)

    # Second dense layer with ReLU activation
    x = Dense(512, activation='relu', name='dense_512')(x)
    # Dropout layer for regularization
    x = Dropout(0.5, name='dropout_2')(x)

    # Output layer with 'softmax' activation for multi-class probability distribution
    outputs = Dense(num_classes, activation='softmax', name='output_phase1')(x)

    model = Model(inputs, outputs, name='mobilenetv2_TransferLearningModel')

    # Compile the Model
    model.compile(
        optimizer=Adam(learning_rate=0.001),
        loss='categorical_crossentropy',
        metrics=['accuracy']
    )

    print("\nModel Summary")
    model.summary()
    print(f"Food Classification Model compiled successfully for {NUM_CLASSES} classes.")

    return model, base_model

# Model Initialization and Compilation
model, base_model = create_food_classification_model(input_shape=(IMG_HEIGHT, IMG_WIDTH, 3), num_classes=NUM_CLASSES)

# Training CNN Model
print(f"\nStarting Training")
print(f"Training for {EPOCHS_PHASE1} epochs.")


callbacks = setup_training_callbacks(patience=3)
history_phase1 = model.fit(train_ds,
                    validation_data=val_ds,
                    epochs=EPOCHS_PHASE1,
                    callbacks=callbacks)

# Analyze training completion
final_epoch = len(history_phase1.history['accuracy'])
final_train_acc = history_phase1.history['accuracy'][-1]
final_val_acc = history_phase1.history['val_accuracy'][-1]
train_val_gap = final_train_acc - final_val_acc

print(f"\nTraining completed at epoch {final_epoch}")
if final_epoch < EPOCHS_PHASE1:
    print("Early stopping activated successfully")

print(f"Final train-validation gap: {train_val_gap:.3f} ({train_val_gap*100:.1f}%)")

"""# Performance Evaluation and Metrics: Feature Extraction"""

# Generate Predictions (Feature Extraction Phase)
# Predict class probabilities for the test dataset
predictions = model.predict(test_ds, verbose=0)
# Convert probabilities to class indices (the final prediction)
predicted_labels = np.argmax(predictions, axis=1)

# Metrics (Precision, Recall, F1-score, Accuracy)
print("\nClassification Report (Feature Extraction):")
print(classification_report(true_labels_int, predicted_labels, target_names=class_names, zero_division=0))

# Accuracy and Loss Plots
print("\nGenerating Accuracy and Loss Plots (Feature Extraction)")
plot_history(history_phase1)

# Confusion Matrix
cm = confusion_matrix(true_labels_int, predicted_labels)
print("\nGenerating Confusion Matrix Plot (Feature Extraction)")

loss, accuracy = model.evaluate(test_ds, verbose=0)

plot_confusion_matrix(cm, class_names, title=f'Confusion Matrix (Acc: {accuracy*100:.2f}%)')

"""# Fine-Tune Model"""

def create_food_classification_ft_model(model, base_model, start_layer):
    """
    Sets up the model for the Fine-Tuning phase.
    Unfreezes the top layers and recompiles with low learning rate.
    """

    # Set Base Model Trainability to TRUE for Fine-Tuning
    base_model.trainable = True

    # Freeze layers up to the 'start_layer' index
    for i, layer in enumerate(base_model.layers):
        if i < (len(base_model.layers) + start_layer):
            layer.trainable = False
        else:
            layer.trainable = True

    # Compile the Model for Fine-Tuning
    model.compile(
    optimizer=Adam(learning_rate=1e-5),
    loss='categorical_crossentropy',
    metrics=['accuracy']
    )

    num_trainable = sum(tf.keras.backend.count_params(w) for w in model.trainable_weights)
    num_frozen = sum(tf.keras.backend.count_params(w) for w in model.non_trainable_weights)

    print(f"\nFine-Tuning Summary")
    print(f"Total Trainable Params: {num_trainable / 1e6:.2f}M")
    print(f"Total Non-Trainable Params: {num_frozen / 1e6:.2f}M")
    print(f"Base model unfrozen from layer {len(base_model.layers) + start_layer} onwards (top {abs(start_layer)} blocks).")

    return model

# Initialize and Compile Model (Fine-Tuning)
ft_model = create_food_classification_ft_model(
    model, base_model, start_layer=FINE_TUNE_START_LAYER_INDEX)

ft_model.summary(expand_nested=True, show_trainable=True)

# Calculate the starting epoch number for fine-tuning
initial_epoch_ft = history_phase1.epoch[-1] + 1 if history_phase1.epoch else 0

callbacks = setup_training_callbacks(patience=5) # Reconfigure callbacks with patience=5 epochs for Fine-Tuning

print(f"\nStarting Fine-Tuning Training ({EPOCHS_PHASE2} epochs)")
ft_history = ft_model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=initial_epoch_ft + EPOCHS_PHASE2, # Total epochs = epochs already run + new fine-tuning epochs
    callbacks=callbacks
)

# Analyze training completion
final_epoch = len(ft_history.history['accuracy'])
final_train_acc = ft_history.history['accuracy'][-1]
final_val_acc = ft_history.history['val_accuracy'][-1]
train_val_gap = final_train_acc - final_val_acc

print(f"\nTraining completed at epoch {final_epoch}")
if final_epoch < (initial_epoch_ft + EPOCHS_PHASE2):
    print("Early stopping activated successfully")

print(f"Final train-validation gap: {train_val_gap:.3f} ({train_val_gap*100:.1f}%)")

"""# Performance Evaluation and Metrics: Fine-Tune"""

# Generate Predictions (Fine-Tuning)
# Predict class probabilities for the test dataset using the fine-tuned model
predictions = ft_model.predict(test_ds, verbose=0)
# Convert probabilities to class indices
predicted_labels = np.argmax(predictions, axis=1)

# Metrics (Precision, Recall, F1-score, Accuracy)
print("\nClassification Report (Fine-Tuning):")
print(classification_report(true_labels_int, predicted_labels, target_names=class_names, zero_division=0))

# Accuracy and Loss Plots
print("\nGenerating Accuracy and Loss Plots (Fine-Tuning)")
plot_history(ft_history)

# Confusion Matrix
cm = confusion_matrix(true_labels_int, predicted_labels)
print("\nGenerating Confusion Matrix Plot (Fine-Tuning))")

loss, accuracy = ft_model.evaluate(test_ds, verbose=0)

plot_confusion_matrix(cm, class_names, title=f'Confusion Matrix (Acc: {accuracy*100:.2f}%)')